export interface Producto {
  idProducto: number;
  codigo: string;
  descripcion: string;
  cantidad: number;
  cantMinima: number;
  bulto: number;
  nombreMedida: string;
  precioCosto: number;
  gananciaPorcentaje: number;
  gananciaNeto: number;
  precioVentaPublico: number;
  ivaPorcentaje: number;
  ivaNeto: number;
  precioLista: number;
  nombreRubro: string;
  ilimitado: boolean;
  publico: boolean;
  destacado: boolean;
  fechaUltimaModificacion: Date;
  estanteria: string;
  estante: string;
  razonSocialProveedor: string;
  nota: string;
  fechaAlta: Date;
  fechaVencimiento: Date;
  eliminado: Date;
  urlImagen: string;
}
