export enum TipoDeComprobante {
  FACTURA_A = 'FACTURA_A', // notas de credito
  FACTURA_B = 'FACTURA_B', // notas de credito
  FACTURA_C = 'FACTURA_C', // notas de credito
  FACTURA_X = 'FACTURA_X', // notas de credito
  FACTURA_Y = 'FACTURA_Y', // notas de credito
  PEDIDO = 'PEDIDO',
  PRESUPUESTO = 'PRESUPUESTO', // notas de credito
  RECIBO = 'RECIBO', // notas de debito
  GASTO = 'GASTO',
  NOTA_CREDITO_A = 'NOTA_CREDITO_A',
  NOTA_CREDITO_B = 'NOTA_CREDITO_B',
  NOTA_CREDITO_C = 'NOTA_CREDITO_C',
  NOTA_CREDITO_X = 'NOTA_CREDITO_X',
  NOTA_CREDITO_Y = 'NOTA_CREDITO_Y',
  NOTA_CREDITO_PRESUPUESTO = 'NOTA_CREDITO_PRESUPUESTO',
  NOTA_DEBITO_A = 'NOTA_DEBITO_A',
  NOTA_DEBITO_B = 'NOTA_DEBITO_B',
  NOTA_DEBITO_C = 'NOTA_DEBITO_C',
  NOTA_DEBITO_X = 'NOTA_DEBITO_X',
  NOTA_DEBITO_Y = 'NOTA_DEBITO_Y',
  NOTA_DEBITO_PRESUPUESTO = 'NOTA_DEBITO_PRESUPUESTO',
  REMITO = 'REMITO',
}
