name: Open Commercial CI

on:
  push:
    branches:
      - master
      - globodeoro
      - merceriaguemes
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build-analyze-deploy:
    name: Build, analyze, dockerize and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.13          
      - name: Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}          
        run: |
          if [ ${{ github.ref_name }} != 'globodeoro' && ${{ github.ref_name }} != 'merceriaguemes' ]; then
            ENV_NAME=
          else
            ENV_NAME=${{ github.ref_name }}
          fi
          npm install
          npm run build          
        shell: bash        
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}       
      - name: Set up QEMU
        if: ${{ github.ref_name == 'globodeoro' || github.ref_name == 'merceriaguemes' }}
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: ${{ github.ref_name == 'globodeoro' || github.ref_name == 'merceriaguemes' }}
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: ${{ github.ref_name == 'globodeoro' || github.ref_name == 'merceriaguemes' }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        if: ${{ github.ref_name == 'globodeoro' || github.ref_name == 'merceriaguemes' }}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: opencommercial/sic-ops-web:${{ github.ref_name }}
